query getExercises($input: GameSettingsInput!) {
  exercises(input: $input) {
    character {
      id
      unicode
      syllValues
    },
    correct,
    questionType,
    answers {
      correct
      displayValue
    }
  }
}