query CompVariants(
	$input: CompVariantsInput! = {
		horizontal: 1
		vertical: 0
		glossenkeil: 0
		diagonalAsc: 0
		diagonalDesc: 0
	}
) {
	compVariants(input: $input) {
		identicalVariants {
			...CompVariant
		}
		similarVariants {
			horizontalMinus {
				...CompVariant
			}
			horizontalPlus {
				...CompVariant
			}
			verticalMinus {
				...CompVariant
			}
			verticalPlus {
				...CompVariant
			}
			glossenkeilMinus {
				...CompVariant
			}
			glossenkeilPlus {
				...CompVariant
			}
			diagonalAscMinus {
				...CompVariant
			}
			diagonalAscPlus {
				...CompVariant
			}
			diagonalDescMinus {
				...CompVariant
			}
			diagonalDescPlus {
				...CompVariant
			}
		}
	}
}
