query test_exercise {
	exercises(
		input: {
			selectedIds: [1]
			numberOfAlternatives: 5
			inclSyll: true
			inclDet: true
			inclLog: true
			translitToCun: true
			cunToTranslit: true
		}
	) {
		character {
			id
		}
	}
}
